### ISSUE TITLE
华为meta10 录制完成后发生崩溃

### ISSUE THREAD

**Issue by chenpdsu** [aserbao/AndroidCamera#17]
java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:80)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:164)
        at com.aserbao.androidcustomcamera.whole.record.beans.MediaObject.stopRecord(MediaObject.java:91)
        at com.aserbao.androidcustomcamera.whole.record.RecorderActivity$MyHandler.handleMessage(RecorderActivity.java:388)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by aserbao** [comment]
两种情况：
1. 录制视频过短
2. 视频数据没有保存完成
做下处理就可以了。
