### ISSUE TITLE
在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题

### ISSUE THREAD

**Issue by zhoushuangli** [aserbao/AndroidCamera#38]

**Comment by aserbao** [comment]
是否有日志?

**Comment by zhoushuangli** [comment]
原有的demo直接跑的，没有任何改动，而且在小米手机上点了暂停录制以后进度条还是在绘制，在小米8和小米9cc都是这样的
2020-08-11 18:50:14.389 13544-13544/com.aserbao.androidcustomcamera E/AndroidRuntime: FATAL EXCEPTION: main
&nbsp;&nbsp;&nbsp; Process: com.aserbao.androidcustomcamera, PID: 13544
&nbsp;&nbsp;&nbsp; java.util.ConcurrentModificationException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at java.util.LinkedList$ListItr.next(LinkedList.java:888)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.aserbao.androidcustomcamera.whole.record.ui.ProgressView.onDraw(ProgressView.java:153)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.view.View.draw(View.java:20234)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.view.View.updateDisplayListIfDirty(View.java:19109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.view.View.draw(View.java:19962)





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aserbao"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 晚上6:47
收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38)





 
是否有日志?

**Comment by zhoushuangli** [comment]
ruguo''

**Comment by zhoushuangli** [comment]
如果你找到问题解决了的话,麻烦更新下demo,因为现在项目中使用了您的个别功能而且在基础上改进了很多,所以,麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aserbao"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 晚上6:47
收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38)





 
是否有日志?

**Comment by aserbao** [comment]
搜一下ConcurrentModificationException 的解决方案，我这边没有小米8和小米9cc

**Comment by yznyan** [comment]
> 如果你找到问题解决了的话,麻烦更新下demo,因为现在项目中使用了您的个别功能而且在基础上改进了很多,所以,麻烦您了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aserbao"<notifications@github.com&gt;; 发送时间: 2020年8月11日(星期二) 晚上6:47 收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38) 是否有日志? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问你解决了

**Comment by zhoushuangli** [comment]
放弃了,bug很多,多个机型测试出现闪崩




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yzn"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 上午10:18
收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38)





  
如果你找到问题解决了的话,麻烦更新下demo,因为现在项目中使用了您的个别功能而且在基础上改进了很多,所以,麻烦您了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aserbao"<notifications@github.com&gt;; 发送时间: 2020年8月11日(星期二) 晚上6:47 收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38) 是否有日志? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好，请问你解决了

**Comment by 24Lathiya** [comment]
I have same problem as mention below in many device. Progress bar is keep drawing after stop recording.
@zhoushuangli @aserbao  Please let me know if any idea to fix it.

**Comment by Lee465357793** [comment]
> 放弃了,bug很多,多个机型测试出现闪崩
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzn"<notifications@github.com&gt;; 发送时间: 2020年9月4日(星期五) 上午10:18 收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38) 如果你找到问题解决了的话,麻烦更新下demo,因为现在项目中使用了您的个别功能而且在基础上改进了很多,所以,麻烦您了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aserbao"<notifications@github.com&gt;; 发送时间: 2020年8月11日(星期二) 晚上6:47 收件人: "aserbao/AndroidCamera"<AndroidCamera@noreply.github.com&gt;; 抄送: "蛋蛋"<554707615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [aserbao/AndroidCamera] 在小米手机上测试发现进度条有问题，会导致闪退，测了两个小米手机同样问题 (#38) 是否有日志? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，请问你解决了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有好用的推荐么？
